"""baseline families and members

Revision ID: 1263357e7636
Revises: 
Create Date: 2025-11-24 22:12:41.176570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1263357e7636'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('role', sa.String(length=50), nullable=True))
    op.alter_column('members', 'gender',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('members', 'dob',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('members', 'mobile',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_column('members', 'relation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('relation', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('members', 'mobile',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('members', 'dob',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('members', 'gender',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_column('members', 'role')
    # ### end Alembic commands ###
