"""switch to family_number

Revision ID: 858c781dbde8
Revises: e3f95fbb2f89
Create Date: 2025-12-09 22:58:43.802776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858c781dbde8'
down_revision: Union[str, Sequence[str], None] = 'e3f95fbb2f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('family_number', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_transactions_family_number'), 'transactions', ['family_number'], unique=False)
    op.drop_column('transactions', 'family_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('family_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_transactions_family_number'), table_name='transactions')
    op.drop_column('transactions', 'family_number')
    # ### end Alembic commands ###
